package controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import modelo.Persona;
import javafx.event.ActionEvent;

import javafx.scene.control.TableView;

public class Ejer_1Controller {
	@FXML
	private Button btnAgregar;
	@FXML
	private TextField txtNombre;
	@FXML
	private TextField txtApellidos;
	@FXML
	private TextField txtEdad;
	@FXML
	private TableView tablaDatos;

	// Event Listener on Button[#btnAgregar].onAction
	@FXML
	public void agregrar(ActionEvent event) {
		// TODO Autogenerated
		String nombre = txtNombre.getText();
		String apellidos = txtApellidos.getText();
		int edad = Integer.parseInt (txtEdad.getText());
		
		Persona persona = new Persona(nombre, apellidos, edad);
		
	}
}
