package controllers;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import modelo.Persona;

import java.net.URL;
import java.util.ResourceBundle;

import config.Messages;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.TableView;

public class Ejer_2Controller implements Initializable{
	@FXML
	private Button btnAgregar;
	@FXML
	private TextField txtNombre;
	@FXML
	private TextField txtApellidos;
	@FXML
	private TextField txtEdad;
	@FXML
	private TableView tablaDatos;
	@FXML
	private TableColumn<Persona, String> columNombre;
	@FXML
	private TableColumn<Persona, String> columApellido;
	@FXML
	private TableColumn<Persona, Integer> columEdad;
	
	private ObservableList<Persona> personas;

	// Event Listener on Button[#btnAgregar].onAction
	@FXML
	public void agregrar(ActionEvent event) {
		// TODO Autogenerated
		String nombre = txtNombre.getText();
		String apellidos = txtApellidos.getText();
		
		try {
			int edad = Integer.parseInt (txtEdad.getText());
			Persona p = new Persona(nombre, apellidos, edad);
			
			if(!personas.contains(p)) {
				//Comprobar el rago de la edad
				if(p.getEdad() > 120 || p.getEdad() < 0) {
					Alert alert = new Alert(Alert.AlertType.ERROR);
					alert.initOwner(this.btnAgregar.getScene().getWindow());
					alert.setHeaderText(null);
					alert.setTitle(Messages.getString("Ejer_2Controller.0")); //$NON-NLS-1$
					alert.setContentText(Messages.getString("Ejer_2Controller.1")); //$NON-NLS-1$
					alert.showAndWait();
				}			
				
				// Asegurarse de que el nombre no esta vacio
				else if(p.getNombre().isEmpty()) {
					Alert alert = new Alert(Alert.AlertType.ERROR);
					alert.initOwner(this.btnAgregar.getScene().getWindow());
					alert.setHeaderText(null);
					alert.setTitle(Messages.getString("Ejer_2Controller.2")); //$NON-NLS-1$
					alert.setContentText(Messages.getString("Ejer_2Controller.3")); //$NON-NLS-1$
					alert.showAndWait();
				}
				
				//Asegurarse de que el apellido no esta vacio
				else if(p.getApellido().isEmpty()) {
					Alert alert = new Alert(Alert.AlertType.ERROR);
					alert.initOwner(this.btnAgregar.getScene().getWindow());
					alert.setHeaderText(null);
					alert.setTitle(Messages.getString("Ejer_2Controller.4")); //$NON-NLS-1$
					alert.setContentText(Messages.getString("Ejer_2Controller.5")); //$NON-NLS-1$
					alert.showAndWait();
				}
				else {
					personas.add(p);
					txtNombre.setText(Messages.getString("Ejer_2Controller.6")); //$NON-NLS-1$
					txtApellidos.setText(Messages.getString("Ejer_2Controller.7")); //$NON-NLS-1$
					txtEdad.setText(Messages.getString("Ejer_2Controller.8")); //$NON-NLS-1$
				}	
			}
			// Comprobar que la persona a introducir no exista ya
			else {
				Alert alert = new Alert(Alert.AlertType.ERROR);
				alert.initOwner(this.btnAgregar.getScene().getWindow());
				alert.setHeaderText(null);
				alert.setTitle(Messages.getString("Ejer_2Controller.9")); //$NON-NLS-1$
				alert.setContentText(Messages.getString("Ejer_2Controller.10")); //$NON-NLS-1$
				alert.showAndWait();
			}
			//Asegurarse de que la edad es un entero
		}catch (Exception e) {
			Alert alert = new Alert(Alert.AlertType.ERROR);
			alert.initOwner(this.btnAgregar.getScene().getWindow());
			alert.setHeaderText(null);
			alert.setTitle(Messages.getString("Ejer_2Controller.11")); //$NON-NLS-1$
			alert.setContentText(Messages.getString("Ejer_2Controller.12")); //$NON-NLS-1$
			alert.showAndWait();
		}

	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		personas = FXCollections.observableArrayList();
		tablaDatos.setItems(personas);
		columNombre.setCellValueFactory(new PropertyValueFactory<Persona, String>(Messages.getString("Ejer_2Controller.13"))); //$NON-NLS-1$
		columApellido.setCellValueFactory(new PropertyValueFactory<Persona, String>(Messages.getString("Ejer_2Controller.14"))); //$NON-NLS-1$
		columEdad.setCellValueFactory(new PropertyValueFactory<Persona, Integer>(Messages.getString("Ejer_2Controller.15"))); //$NON-NLS-1$
	}
}
