package controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class Alumnos_IngresarDatosController {
	@FXML
	private Button btnGuardarAlum;
	@FXML
	private Button btnCancelarAlum;
	@FXML
	private TextField txtNombreAlum;
	@FXML
	private TextField txtApellido1Alum;
	@FXML
	private TextField txtApellido2Alum;
	@FXML
	private TextField txtDNI;

	// Event Listener on Button[#btnGuardarAlum].onAction
	@FXML
	public void guardarAlum(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCancelarAlum].onAction
	@FXML
	public void cancelarAlum(ActionEvent event) {
		// TODO Autogenerated
	}
}
