package controllers;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.control.TableColumn;

public class Historico_Controller {
	@FXML
	private ComboBox cmbAlumnos;
	@FXML
	private ComboBox cmbLibro;
	@FXML
	private TextField txtBuscarHistorico;
	@FXML
	private TableColumn columIDHistorico;
	@FXML
	private TableColumn columDNIHistorico;
	@FXML
	private TableColumn columCODHistorico;
	@FXML
	private TableColumn columFechaPrestamoHistorico;
	@FXML
	private TableColumn columFechaDevolHistorico;

	// Event Listener on ComboBox[#cmbAlumnos].onAction
	@FXML
	public void filtrarAlumnos(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#cmbLibro].onAction
	@FXML
	public void filtrarLibros(ActionEvent event) {
		// TODO Autogenerated
	}
}
