package controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.MenuBar;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class LibrosController {
	@FXML
	private TableView tablaLibros;
	@FXML
	private TableColumn columTitulo;
	@FXML
	private TableColumn columAutor;
	@FXML
	private TableColumn columEditorial;
	@FXML
	private TableColumn columEstado;
	@FXML
	private MenuBar menu;
	@FXML
	private TextField txtBuscarLibro;
	@FXML
	private Button btnPrestarLibro;
	@FXML
	private Button btnCrearLibro;
	@FXML
	private Button btnModificarLibro;
	@FXML
	private Button btnBorrarLibro;
	@FXML
	private TableView tablaAlumnos;
	@FXML
	private TableColumn columDNI;
	@FXML
	private TableColumn columNombre;
	@FXML
	private TableColumn columApe1;
	@FXML
	private TableColumn columApe2;
	@FXML
	private TextField txtBuscarAlumno;
	@FXML
	private Button btnCrearAlumno;
	@FXML
	private Button btnModificarALumno;
	@FXML
	private Button btnBorrarAlumno;

	// Event Listener on Button[#btnPrestarLibro].onAction
	@FXML
	public void prestarLibro(ActionEvent event) {
		// TODO Autogenerated
	}
}
