package controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;
import modelo.Libro;
import javafx.event.ActionEvent;

public class Libros_IngresarDatos_Controller {
	@FXML
	private Button btnGuardarLibro;
	@FXML
	private Button btnCancelarLibro;
	@FXML
	private TextField txtAutor;
	@FXML
	private TextField txtEditorial;
	@FXML
	private TextField txtTitulo;
	
	private Libro l;

	// Event Listener on Button[#btnGuardarLibro].onAction
	@FXML
	public void guardarAlum(ActionEvent event) {
		// TODO Autogenerated
	}
	
	public Libro getLibro()	{
		return l;
	}
	


	// Event Listener on Button[#btnCancelarLibro].onAction
	@FXML
	public void cancelarAlum(ActionEvent event) {
		Stage myStage =(Stage) this.btnCancelarLibro.getScene().getWindow();
		myStage.close();
	}
}
