package controllers;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import modelo.Libro;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.MenuBar;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class MainController implements Initializable{
	@FXML
	private TableView<Libro> tablaLibros;
	@FXML
	private TableColumn<Libro, String> columTitulo;
	@FXML
	private TableColumn<Libro, String> columAutor;
	@FXML
	private TableColumn<Libro, String> columEditorial;
	@FXML
	private TableColumn<Libro, String> columEstado;
	@FXML
	private MenuBar menu;
	@FXML
	private TextField txtBuscarLibro;
	@FXML
	private Button btnPrestarLibro;
	@FXML
	private Button btnCrearLibro;
	@FXML
	private Button btnModificarLibro;
	@FXML
	private Button btnBorrarLibro;
	@FXML
	private TableView tablaAlumnos;
	@FXML
	private TableColumn columDNI;
	@FXML
	private TableColumn columNombre;
	@FXML
	private TableColumn columApe1;
	@FXML
	private TableColumn columApe2;
	@FXML
	private TextField txtBuscarAlumno;
	@FXML
	private Button btnCrearAlumno;
	@FXML
	private Button btnModificarALumno;
	@FXML
	private Button btnBorrarAlumno;

	// Event Listener on Button[#btnPrestarLibro].onAction
	@FXML
	public void prestarLibro(ActionEvent event) {
		// TODO Autogenerated
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
	}
}
