package controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.TableView;

public class PrestamosController {
	@FXML
	private TableView tablaPrestamo;
	@FXML
	private Button btnDevolverLibro;
	@FXML
	private Button btnVolverPrestamo;
	@FXML
	private TextField txtBuscarPrestamo;

	// Event Listener on Button[#btnDevolverLibro].onAction
	@FXML
	public void devolverLibro(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnVolverPrestamo].onAction
	@FXML
	public void volverPrestamo(ActionEvent event) {
		// TODO Autogenerated
	}
}
